<div class="container">
    <div class="row">
        <h2 class="text-center">Add Interest</h2>
        <div class="col-lg-offset-3 col-lg-6">
            <a href="interest/list">List interest</a>
            <a href="search">Search</a>
            <form action="#" method="post">
                <div class="form-group">
                    <label for="interest-name">Name</label>
                    <input type="text" class="form-control" id="interest-name" name="interest-name" placeholder="Name:">
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-success" name="submit" value="Submit">
                </div>
            </form>
        </div>
    </div>
</div>