<div class="container">
    <div class="row">
        <h2 class="text-center">Search action</h2>
        <div class="search-form">
            <div class="col-lg-6 col-lg-offset-3 clearfix">
                <form action="#" method="post">
                    <div class="form-group">
                        <label for="first-name">First name</label>
                        <input type="text" name="first-name" class="form-control" id="first-name" placeholder="First name:">
                    </div>
                    <div class="form-group">
                        <label for="last-name">Last name</label>
                        <input type="text" name="last-name" class="form-control" id="last-name" placeholder="Last name:">
                    </div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="email" name="email" class="form-control" id="email" placeholder="Email:">
                    </div>
                    <div>
                        <label for="age">Age</label>
                        <div class="form-group">
                            <input type="text" class="form-control" id="min-age" placeholder="Min">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" id="max-age" placeholder="Max">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="interest">Interest</label>
                        <hr>
                        <label class="checkbox-inline" for="football">
                            <input type="checkbox" name="football" id="football" value="football">Football
                        </label><br>
                        <label class="checkbox-inline" for="paint">
                            <input type="checkbox" name="paint" id="paint" value="paint">Paint
                        </label><br>
                        <label class="checkbox-inline" for="write">
                            <input type="checkbox" name="write" id="write" value="write">Write
                        </label><br>
                    </div>
                    <div class="form-group">
                        <input type="submit" name="submit" class="btn btn-success">
                        <input type="reset" class="btn btn-danger" value="Clear">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>