<div class="container">
    <div class="row clearfix">
        <h2 class="text-center">Search action</h2>
        <div class="search-form">
            <div class="col-lg-6 col-lg-offset-3">
                <a href="interest/add" class="btn btn-primary">Add interest</a>
                <a href="register" class="btn btn-primary">Register</a>
                <form action="#" method="post" novalidate>
                    <div class="form-group">
                        <label for="first-name">First name</label>
                        <input type="text" name="first-name" class="form-control" id="first-name" placeholder="First name:">
                    </div>
                    <div class="form-group">
                        <label for="last-name">Last name</label>
                        <input type="text" name="last-name" class="form-control" id="last-name" placeholder="Last name:">
                    </div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="email" name="email" class="form-control" id="email" placeholder="Email:">
                    </div>
                    <div>
                        <label for="age">Age</label>
                        <div class="form-group">
                            <input type="text" class="form-control" name="min-age" id="min-age" placeholder="Min">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" name="max-age" id="max-age" placeholder="Max">
                        </div>
                    </div>
                    <div>
                        <label for="created">Created</label>
                        <div class="form-group">
                            <input type="date" class="form-control" name="min-created" id="min-created">
                        </div>
                        <div class="form-group">
                            <input type="date" class="form-control" name="max-created" id="max-created">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="interest">Interest</label>
                        <hr>
                        <?php foreach ($data as $item): ?>
                            <label class="checkbox-inline" for="<?=$item->name;?>">
                                <input type="checkbox" name="<?=$item->name;?>-interest" id="<?=$item->name;?>" value="<?=$item->id;?>"><?=$item->name;?>
                            </label><br>
                        <?php endforeach;?>
                    </div>
                    <div class="form-group">
                        <input type="submit" name="submit" class="btn btn-success" value="Submit">
                        <input type="reset" class="btn btn-danger" value="Clear">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>