<div class="container">
    <div class="row">
        <h2 class="text-center">User List</h2>
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>Id</th>
                <th>First name</th>
                <th>Last name</th>
                <th>Age</th>
                <th>Email</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($data as $user): ?>
                <tr>
                    <td><?=$user->id;?></td>
                    <td><?=$user->first_name;?></td>
                    <td><?=$user->last_name;?></td>
                    <td><?=$user->age;?></td>
                    <td><?=$user->email;?></td>
                </tr>
            <?php endforeach;?>
            </tbody>
        </table>
    </div>
</div>