<div class="container">
    <div class="row">
        <h2 class="text-center">User interest</h2>
        <div class="col-lg-offset-3 col-lg-6">
            <a href="<?=ROOT_DIR;?>search" class="btn btn-primary">Search</a>
<!--            Full user name-->
            <b><p><?=$data['user']->first_name . ' ' . $data['user']->last_name;?></p></b>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>Interest</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($data['interest'] as $interest): ?>
                    <tr>
                        <td><?=$interest->name;?></td>
                    </tr>
                <?php endforeach;?>
                </tbody>
            </table>
        </div>
    </div>
</div>